### ISSUE TITLE
Add track-specific information to Protein Translation.

### ISSUE THREAD

**Issue by BNAndras** [exercism/cairo#109]
The Protein Translation exercise deviates from the upstream canonical data by including additional proteins not listed in the instructions. Generally, that's fine, but in this circumstance, students will likely get confused since this exercise is often marked as an easy or medium exercise, not a hard one. Also the instructions tab prominently says not all codon sequences and amino acids are important to the exercise. The table at the end is also introduced as showing all the codons and acids.

We shouldn't directly edit the instructions since it makes syncing upstream changes harder. `configlet` will just overwrite whatever's currently in the instructions so you'd need to add the info back manually. A better approach is to make an instructions.append.md file that includes track-specific content and is appended to the end of the instructions. There, it'd be good to include an updated table or just mention that the Cairo track is using more amino acids than what's in the initial table. That'll alert the student that they need to pay closer attention.

**Comment by misicnenad** [comment]
Everything except for the solution itself (_lib.cairo_ and _example.cairo_) was copied from Rust's track, so I didn't modify much as I assumed everything's alright.

Will compare the canonical data with what we have, and update as per your suggestions.

**Comment by 0xNeshi** [comment]
Will rewrite the whole exercise to completely match the [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/protein-translation/canonical-data.json)
