### ISSUE TITLE
Exercises to add

### ISSUE THREAD

**Issue by BNAndras** [exercism/cairo#113]
Exercises to add

TO ADD
- [x] https://github.com/exercism/cairo/issues/164
- [x] https://github.com/exercism/cairo/issues/179
- [x] https://github.com/exercism/cairo/issues/199
- [x] https://github.com/exercism/cairo/issues/211
- [x] https://github.com/exercism/cairo/issues/222
- [x] https://github.com/exercism/cairo/issues/223
- [x] https://github.com/exercism/cairo/issues/243

DONE
- [x] acronym #147
- [x] bob #151
- [x] collatz-conjecture #114
- [x] darts #111
- [x] difference-of-squares #129
- [x] eliuds-eggs #128
- [x] hamming #127
- [x] isogram #140 
- [x] matching-brackets #136
- [x] pangram #133
- [x] pascals-triangle #146
- [x] phone-number #142
- [x] raindrops #115
- [x] reverse-string #110
- [x] rna-transcription #132
- [x] rotational-cipher #130
- [x] secret-handshake #141
- [x] square-root #112
- [x] yacht #277

**Comment by BNAndras** [comment]
I'll add luhn (week 12), phone-number (week 36), and isogram (week 37) as well.

**Comment by BNAndras** [comment]
I'll add bob (week 38) and phone-number (week 36). There are some exercises besides the #48in24 ones I can toss in there namely `atbash-cipher`, `etl`, `perfect-numbers`, `resistor-color`, `resistor-color-duo`, and `triangle`.  I think that'd be it for a while since I'd need to learn more about traits for some of the other exercises I could bring over.

**Comment by 0xNeshi** [comment]
@BNAndras sounds awesome, go for it! :heart:
