### ISSUE TITLE
Write the "Error Handling" Concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#125]
Official docs: 
https://book.cairo-lang.org/ch09-00-error-handling.html

The concept should include descriptions for both recoverable (`Result`) and unrecoverable (`panic`) errors.

The idea is to have a short and to-the-point article about the concept without going too deep. Avoid just copy/pasting everything from The Cairo Book; the Book should be used as a more in-depth learning resource for students after they finish the concept on Exercism (or they can use it in parallel). 

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use the following Rust's concept as inspiration for the format:
https://github.com/exercism/rust/blob/main/concepts/structs/about.md

**Comment by xiakshay** [comment]
Assign this to me.

**Comment by xiakshay** [comment]
Hey, Can I use own simple example? or I have to write from Cairo website.

**Comment by 0xNeshi** [comment]
@xiakshay of course you can think of your own examples, that's even better than copy/pasting!

**Comment by xiakshay** [comment]
Error Handling Concept #125 #131
Added the concept, ready to merge.

**Comment by xiakshay** [comment]
Updated the file according to the reviews.

**Comment by xiakshay** [comment]
Updated the files once again according to the reviews. #131

**Comment by xiakshay** [comment]
Made final changes and resolved all the issues. Please check and let me know if there are any discrepancies.

**Comment by xiakshay** [comment]
Thank you so much 😊
