### ISSUE TITLE
Turn `lucians-luscious-lasagna` into a Concept Exercise

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#148]
Towards #103 

You can basically copy/paste [Rust's metadata-related files](https://github.com/exercism/rust/tree/main/exercises/concept/lucians-luscious-lasagna) (introduction.md, instructions, hints etc.) and also copy/paste the [existing exercise implementation](https://github.com/exercism/cairo/tree/main/exercises/practice/lucians-luscious-lasagna).

In [_config.json_](https://exercism.org/docs/building/tracks/config-json#h-concept-exercises):
- mark the concept's status as "beta"
- mark that concepts being learned are `"functions"`

**Comment by 0xNeshi** [comment]
@ErikSchierboom is it OK to turn this exercise from "practice" into "concept"? It is a very natural transition, given the exercise

**Comment by ErikSchierboom** [comment]
> is it OK to turn this exercise from "practice" into "concept"? It is a very natural transition, given the exercise

It should never really have been a practice exercise in the first place, but that aside, I _think_ it is fine. We'll see when we sync the exercise

**Comment by 0xNeshi** [comment]
> It should never really have been a practice exercise in the first place

In retrospect, I agree
