### ISSUE TITLE
Add Practice Exercise: `etl`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#179]
Closes https://github.com/exercism/cairo/issues/113

Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/etl
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise etl`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/etl/canonical-data.json

**Comment by 0xNeshi** [comment]
@BNAndras are you still working on this?

**Comment by BNAndras** [comment]
I likely won't get to this one until early January so if you want to unassign me, go ahead.
