### ISSUE TITLE
Add Practice Exercise: `grep`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#188]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/grep
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise grep`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/grep/canonical-data.json

**Comment by Falilah** [comment]
Can I have this?

**Comment by 0xNeshi** [comment]
@Falilah go for it!

And thank you for your numerous contributions, you're truly awesome :heart_on_fire:

**Comment by Falilah** [comment]
oooh, I was going to challenge myself on how cairo works with files 😀.
 I will go for another one.
 
it's a pleasure.
thank you for the opportunity 😇
