### ISSUE TITLE
Add Practice Exercise: `lens-person`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#197]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/lens-person
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise lens-person`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/lens-person/canonical-data.json

**Comment by BNAndras** [comment]
This exercise is currently foregone so we can close this issue until which time we can implement the exercise.

**Comment by 0xNeshi** [comment]
https://github.com/exercism/cairo/pull/254
