### ISSUE TITLE
Add Practice Exercise: `space-age`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#235]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/space-age
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise space-age`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/space-age/canonical-data.json

Even though this exercise requires the use of floating point numbers (which are not supported by Cairo), we should implement it in a way that works without them. This is usually achieved by the use of ["basis points"](https://www.investopedia.com/terms/b/basispoint.asp) - in short, the decimal part of the float number is represented by additional decimals being added to the Cairo integer, enabling calculations. Basically all numbers are multiplied by some multiple of the number 10, converting the float number into a regular (but expanded) integer. So `10.34` becomes `10.34 * 100 = 1034`.

- Given the above, all canonical test case results (float numbers) should be multiplied by 100.
- add _instructions.amend.md_ explaining the above.

**Comment by BNAndras** [comment]
This one involves floating point math so I was on the fence about proposing it earlier. If the solution uses multiplication to avoid using floats at any point, that might work. However, that approach feels a bit convoluted for what generally is an easier exercise. Just because we can do it doesn't necessarily mean it's a great fit for the track. On the other hand, it can highlight some potential limitations with Cairo and how to work around them so there's some use there. We'll definitely want to provide an instructions-append highlighting the situation going into the exercise.

**Comment by 0xNeshi** [comment]
> On the other hand, it can highlight some potential limitations with Cairo and how to work around them so there's some use there.

Exactly this :point_up: 
Given that one of the main current uses for Cairo is for smart contract development, where there is a need to handle decimals without the use of floating point numbers, I think this would be a great exercise to teach students how do exactly this.

> We'll definitely want to provide an instructions-append highlighting the situation going into the exercise.

Agreed.

Updating the description.

**Comment by 0xNeshi** [comment]
@BNAndras I created a PR #290  for this without checking whether the issue was assigned, apologies

**Comment by BNAndras** [comment]
No worries
