### ISSUE TITLE
Add Practice Exercise: `triangle`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#243]
Towards https://github.com/exercism/cairo/issues/113

Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/triangle
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise triangle`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/triangle/canonical-data.json

**Comment by BNAndras** [comment]
For this exercise, there are generally two approaches I've seen for implementation. We provide three functions that check if the sides correspond to a particular kind of triangle, returning true or false (see https://github.com/exercism/csharp/blob/main/exercises/practice/triangle/Triangle.cs). The other approach is that we have a single function that checks the sides and returns what kind of triangle it is (see https://github.com/exercism/elixir/blob/main/exercises/practice/triangle/lib/triangle.ex). In the later case, some of the tests should be excluded where a triangle may be more than one type based on the sides.

Any preference?

**Comment by 0xNeshi** [comment]
Let's go with the former version, as it aligns with the "official" problem specification (https://github.com/exercism/problem-specifications/blob/main/exercises/triangle/canonical-data.json).
