### ISSUE TITLE
Add Practice Exercise: `two-fer`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#246]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/two-fer
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise two-fer`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/two-fer/canonical-data.json

**Comment by BNAndras** [comment]
I'm thinking of using an Option parameter here. This tends to be a simpler exercise often revolving around default parameter values and string concatenation / interpolation. Therefore, I think we should add an instructions-append file briefly highlighting what an Option is and provide links to documentation. That's what the Python track does a lot of the time, and it doesn't have to be a big thing.

**Comment by 0xNeshi** [comment]
Sounds good to me
