### ISSUE TITLE
Add Practice Exercise: `word-search`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#249]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/word-search
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise word-search`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/word-search/canonical-data.json

**Comment by Falilah** [comment]
can I take this?

**Comment by 0xNeshi** [comment]
Of course :) 
To give you a tip that you may find useful when writing test cases: `scarb fmt` might inline your test table inputs, so to avoid that use `#[cairofmt::skip]`, similar to how it's done for [minesweeper](https://github.com/exercism/cairo/blob/main/exercises/practice/minesweeper/tests/minesweeper.cairo#L40).

Let's say you write your table like the following, and you want `scarb fmt` to keep _not_ format this input from [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/word-search/canonical-data.json#L152):

```rust
    let table = array![
        "camdcimgtc",
        "jefblpepre",
        "clojurermt",
    ],
```

Running `scarb fmt` without annotating this with the above attr:

```rust
    let table = array!["camdcimgtc", "jefblpepre", "clojurermt"];
```

But with this attr it stays the same:

```rust
    #[cairofmt::skip]
    let table = array![
        "camdcimgtc",
        "jefblpepre",
        "clojurermt",
    ];
```
