### ISSUE TITLE
Add Practice Exercise: `wordy`

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#250]
Problem specification:
https://github.com/exercism/problem-specifications/tree/main/exercises/wordy
    
TODO:
    
- generate the exercise with `./bin/fetch-configlet && ./bin/configlet create --practice-exercise wordy`
- check if any of the existing tracks (examples below) implement the exercise and you can reuse the implementation:
    - Go: https://github.com/exercism/go/tree/main/exercises/practice
    - Rust: https://github.com/exercism/rust/tree/main/exercises/practice
    - Python: https://github.com/exercism/python/tree/main/exercises/practice
- use exercise's _canonical-data.json_ to see which test cases to implement:
    https://github.com/exercism/problem-specifications/blob/main/exercises/wordy/canonical-data.json

**Comment by Ephraim-nonso** [comment]
Let me take this.

**Comment by Ephraim-nonso** [comment]
Hi @0xNeshi 

I've been facing some difficulty manipulating strings especially in the area of comparing a fraction of sentence. In the meantime, can I take another task that I can quickly solve the practice exercise. 

Just wanted to update you on the progress of this particular issue.

**Comment by 0xNeshi** [comment]
@Ephraim-nonso imo the most straightforward solution is [Go's](https://github.com/exercism/go/blob/main/exercises/practice/wordy/.meta/example.go), and it being fairly imperative, it is the most easily translated to Cairo.

You can always split a sentence into words with the following pseudocode:
```rust
words = []
current_word = ""
for ch in string {
    if ch != empty_space {
        current_word += ch // in Cairo, use ByteArray::append_byte to convert ASCII number to actual ByteArray char
    } else {
        words.append(current_word)
        current_word = ""
    }
}
words.append(current) // last char should be '?', and we append it as well
```
After this, the algorithm is pretty much the same is in [Go's implementation](https://github.com/exercism/go/blob/main/exercises/practice/wordy/.meta/example.go) and string comparison should be easier as well.
It's not particularly clever, but it doesn't have to be. We aim for ease of understanding and idiomatic Cairo code.

---
If you still think you'd like to work on something else, I think the easiest tasks would be to add Concept exercises, they are mostly at [the top of the issues list](https://github.com/exercism/cairo/issues). You can choose any other issue to work on as well, there are still many other practice exercises and even some concepts to be written as well. Let me know what you'd like to work on, and I'll reassign you.
