### ISSUE TITLE
Example solutions timing out in online editor

### ISSUE THREAD

**Issue by BNAndras** [exercism/cairo#276]
The example solutions for `bob` and `perfect-numbers` both time out consistently when submitted through the online editor. Perhaps the verification CI should also check whether an example solution passes within the time allocated to the test runner (15 - 20 seconds).

**Comment by BNAndras** [comment]
`acronym` also times out.

**Comment by 0xNeshi** [comment]
That's interesting. I just tested all of these out both with `./bin/verify-exercises` in _exercism/cairo_ and by simulating the in-editor run with `./bin/run-in-docker.sh` in _exercism/cairo-test-runner_, and in all cases the test run ends within ~10 seconds. 
This might indicate that the problem lies somewhere else. Were there similar issues with other tracks in the past @BNAndras ?

**Comment by BNAndras** [comment]
It's happening on `yacht` too. I'd expect some exercises to have solutions that time out intermittently if the average time spent is near the timeout threshold. Students have brought that up, and we typically say try a few times.

I don't know about how the test runner is set up, but one approach might be to see if there's anything like packages installed during runtime that we we can cache inside the Docker image and then copy over to where it's needed. Rust does that I believe. That'd give solutions a little more time to run.

**Comment by BNAndras** [comment]
Yacht went through after five tries. Hooray!

**Comment by 0xNeshi** [comment]
> I don't know about how the test runner is set up, but one approach might be to see if there's anything like packages installed during runtime that we we can cache inside the Docker image and then copy over to where it's needed. Rust does that I believe. That'd give solutions a little more time to run.

We do not install nor do we depend on any 3rd party packages, we use only the core Cairo package. I think this might be an issue unrelated to the track

**Comment by 0xNeshi** [comment]
@BNAndras do you have any new info on this issue? I'm inclined to close it, as it doesn't seem related to the track

**Comment by BNAndras** [comment]
I think upgrading Cairo may have contributed (or not) but I retried several timed out exercises and they all worked.
