### ISSUE TITLE
Write the "Strings" concept

### ISSUE THREAD

**Issue by misicnenad** [exercism/cairo#31]
Official docs: 
https://book.cairo-lang.org/ch02-02-data-types.html#string-types

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use "Felt Type" as inspiration for format:
https://github.com/exercism/cairo/tree/main/concepts/felts

**Comment by Ephraim-nonso** [comment]
@misicnenad Let me work on this task.
