### ISSUE TITLE
Write the "Felt Type" concept

### ISSUE THREAD

**Issue by misicnenad** [exercism/cairo#33]
Official docs: 
https://book.cairo-lang.org/ch02-02-data-types.html#felt-type

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use Python track's concepts as inspiration for format:
https://github.com/exercism/python/tree/main/concepts/

**Comment by rajeebkm** [comment]
Please assign to me.

**Comment by misicnenad** [comment]
@rajeebkm let's tackle one issue at a time, I assigned you to https://github.com/exercism/cairo/issues/33
