### ISSUE TITLE
Write the "Enums" concept

### ISSUE THREAD

**Issue by misicnenad** [exercism/cairo#36]
Official docs: 
https://book.cairo-lang.org/ch06-01-enums.html
https://starknet-by-example.voyager.online/getting-started/cairo_cheatsheet/enums.html

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use "The Felt Type" as inspiration for format:
https://github.com/exercism/cairo/tree/main/concepts/felts

**Comment by Ephraim-nonso** [comment]
Let me work on this.
