### ISSUE TITLE
Write the "Control Flow" concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#39]
Official docs: 
https://book.cairo-lang.org/ch02-05-control-flow.html
https://book.cairo-lang.org/ch06-03-concise-control-flow-with-if-let-and-while-let.html

The idea is to have a short and to-the-point article about the concept. Avoid copy/pasting everything from The Cairo Book; the Book should be used as a more in-depth learning resource for students after they finish the concept on Exercism (or they can use it in parallel). 

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use the following Rust's concept as inspiration for the format:
https://github.com/exercism/rust/blob/main/concepts/structs/about.md

**Comment by Falilah** [comment]
can I take this?

**Comment by misicnenad** [comment]
Of course!
