### ISSUE TITLE
Write the "Traits" concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#41]
Official docs: 
https://book.cairo-lang.org/ch08-02-traits-in-cairo.html

The idea is to have a short and to-the-point article about the concept. Avoid copy/pasting everything from The Cairo Book; the Book should be used as a more in-depth learning resource for students after they finish the concept on Exercism (or they can use it in parallel). 

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use the following Rust's concept as inspiration for the format:
https://github.com/exercism/rust/blob/main/concepts/structs/about.md

**Comment by Ephraim-nonso** [comment]
Let me work on this.

**Comment by misicnenad** [comment]
You got it

**Comment by 0xNeshi** [comment]
@Ephraim-nonso how's the PR coming along, need more time?

**Comment by Ephraim-nonso** [comment]
It's going well. I'll need some more time.

**Comment by Ephraim-nonso** [comment]
@0xNeshi I have made a PR for the trait concepts. Do kindly let me know where to make changes. Thank you.
