### ISSUE TITLE
Write the "Structs" concept

### ISSUE THREAD

**Issue by misicnenad** [exercism/cairo#42]
Official docs: 
https://book.cairo-lang.org/ch05-00-using-structs-to-structure-related-data.html

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use Rust's "Structs" concept as inspiration for format:
https://github.com/exercism/rust/blob/main/concepts/structs/about.md

**Comment by okhaimie-dev** [comment]
@misicnenad assign this to me

**Comment by misicnenad** [comment]
@okhaimie-dev how's the concept progressing? 

Let me know if you're having any difficulties, maybe I can help

**Comment by okhaimie-dev** [comment]
I will reach out to you today. and try to complete this before the weekend.
