### ISSUE TITLE
Write the "Type Conversion" concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#44]
Official docs: 
https://book.cairo-lang.org/ch02-02-data-types.html#type-conversion
https://book.cairo-lang.org/ch05-02-an-example-program-using-structs.html#custom-type-conversion

The idea is to have a short and to-the-point article about the concept. Avoid copy/pasting everything from The Cairo Book; the Book should be used as a more in-depth learning resource for students after they finish the concept on Exercism (or they can use it in parallel). 

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use the following Rust's concept as inspiration for the format:
https://github.com/exercism/csharp/blob/main/concepts/structs/about.md

**Comment by ErikSchierboom** [comment]
Just a minor comment: the rust track's syllabus is still quite a work in progress one. For exercises and examples of how to write concept exercises I would suggest looking at tracks like Elixir, Python or C#

**Comment by misicnenad** [comment]
Will update the issue descriptions to point to one of those, thanks :+1:
