### ISSUE TITLE
Write the "Printing" concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#51]
Official docs: 
https://book.cairo-lang.org/ch11-08-printing.html

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use "Felt Type" as inspiration for format:
https://github.com/exercism/cairo/tree/main/concepts/felts

**Comment by Gobinath-B** [comment]
may i do this task? @misicnenad

**Comment by misicnenad** [comment]
@Gobinath-B of course! Assigned you to the issue

**Comment by misicnenad** [comment]
@Gobinath-B how's the work going? Do you have a draft I could look at, maybe I can help you speed things up?

**Comment by okhaimie-dev** [comment]
@misicnenad also assign this to me.

**Comment by misicnenad** [comment]
@okhaimie-dev once you're done with structs work, let me know which issue you'd like to work on first - this one or the ["mutability" one](https://github.com/exercism/cairo/issues/54#issuecomment-2238174933).

It's best to work on one issue at a time; it both allows you to focus on one thing, and it allows more other devs to work on free issues in parallel

**Comment by okhaimie-dev** [comment]
@misicnenad I already made a PR for both `Struct` and `Mut`

**Comment by misicnenad** [comment]
@okhaimie-dev loving the initiative, assigning you to this as well!

**Comment by misicnenad** [comment]
@okhaimie-dev you still working on this?
