### ISSUE TITLE
Write the "Mutability" concept

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#54]
Official docs: 
https://book.cairo-lang.org/ch02-01-variables-and-mutability.html

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

Use Rust track's "Mutability" concept as inspiration for format:
https://github.com/exercism/rust/tree/main/concepts/mutability

**Comment by okhaimie-dev** [comment]
@misicnenad can you assign this to me next

**Comment by misicnenad** [comment]
@okhaimie-dev sure thing! Will assign you once Structs concept work is finished.
Do note that the issue can still be picked up by other devs if they ask for it before you're done with structs

**Comment by okhaimie-dev** [comment]
qq @misicnenad just to clarify this section is on general Cairo mutability, and not related to State Mutability in Starknet contracts?

re: https://starknet-by-example.voyager.online/getting-started/basics/visibility-mutability.html#state-mutability

**Comment by misicnenad** [comment]
That is correct, we are focusing solely on Cairo
