### ISSUE TITLE
Write the "Ownership" concept

### ISSUE THREAD

**Issue by misicnenad** [exercism/cairo#72]
Official docs: 
https://book.cairo-lang.org/ch04-00-understanding-ownership.html

---
Exercism Concepts docs:
https://exercism.org/docs/building/tracks/concepts

**Comment by Falilah** [comment]
Hi can I take this?

**Comment by misicnenad** [comment]
@Falilah sure thing! Ping if you need any guidance

**Comment by misicnenad** [comment]
That is correct!
